@startuml

package App-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.tscn]] {
    class App  {
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs ScriptFile]]
        [Provisions]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:32 IAppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
        --
        [Nodes]
        Menu - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs Script]]
        Splash - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs Script]]
        [Properties]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:50 AnimationPlayer]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:41 AppBinding]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:39 AppLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/state/AppLogic.Output.cs Script]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:38 AppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:49 BlankScreen]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:25 Game]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs Script]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:48 GamePreview]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:26 Instantiator]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/utils/Instantiator.cs Script]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:47 Menu]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs Script]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:51 Splash]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs Script]]
        --
        [Methods]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:15 _Notification()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:150 FadeInFromBlack()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:156 FadeToBlack()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:162 HideMenus()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:55 Initialize()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:134 OnAnimationFinished()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:168 OnExitTree()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:132 OnLoadGame()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:130 OnNewGame()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:73 OnReady()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/App.cs:180 OnSaveFileLoaded()]]
    }
    class Menu  {
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs ScriptFile]]
        [Properties]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:48 AccessibilityLive]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:22 LoadGameButton]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:20 NewGameButton]]
        --
        [Methods]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:17 _Notification()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:49 GetAccessibilityLive()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:39 OnExitTree()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:46 OnLoadGamePressed()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:45 OnNewGamePressed()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/Menu.cs:33 OnReady()]]
    }
    class Splash  {
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs ScriptFile]]
        [Dependencies]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:21 AppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
        --
        [Properties]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:43 AccessibilityLive]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:16 AnimationPlayer]]
        --
        [Methods]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:34 _Input()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:13 _Notification()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:44 GetAccessibilityLive()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:31 OnAnimationFinished()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:28 OnExitTree()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/menu/splash/Splash.cs:25 OnReady()]]
    }
    class AppRepo  {
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs ScriptFile]]
        [Interface Methods]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs:58 OnEnterGame()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs:59 OnExitGame()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs:56 OnMainMenuEntered()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs:54 SkipSplashScreen()]]
        [Methods]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs:63 Dispose()]]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs:80 Dispose()]]
    }
    package Game-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.tscn]] {
        class Game  {
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs ScriptFile]]
            [Dependencies]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:74 AppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
            [Provisions]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:68 IGameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
            --
            [Nodes]
            PlayerCamera - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs Script]]
            Player - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs Script]]
            Map - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs Script]]
            InGameUi - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs Script]]
            InGameAudio - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs Script]]
            DeathMenu - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs Script]]
            WinMenu - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs Script]]
            PauseMenu - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [Properties]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:60 DeathMenu]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:36 EntityTable]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:34 Environment]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:33 FileSystem]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:48 GameBinding]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:39 GameChunk]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:46 GameLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/state/states/Paused.Saving.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:45 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:59 InGameUi]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:31 JsonOptions]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:58 Map]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:62 PauseMenu]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:56 Player]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:54 PlayerCamera]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs Script]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:38 SaveFile]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:35 SaveFilePath]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:61 WinMenu]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs Script]]
            --
            [Interface Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:279 LoadExistingGame()]]
            [Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:235 _Input()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:26 _Notification()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:285 FinishedLoadingSaveFile()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:261 OnDeathMenuTransitioned()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:264 OnExitTree()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:243 OnMainMenu()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:258 OnPauseMenuSaveRequested()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:255 OnPauseMenuTransitioned()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:147 OnResolved()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:246 OnResume()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:249 OnStart()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:252 OnWinMenuTransitioned()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:288 SetPauseMode()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/Game.cs:78 Setup()]]
        }
        package PlayerCamera-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.tscn]] {
            class PlayerCamera  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:72 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Interface Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:113 CameraBasis]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:109 CameraLocalPosition]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:74 CameraLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/State/states/PlayerCameraLogic.State.InputEnabled.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:110 GimbalRotationHorizontal]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:111 GimbalRotationVertical]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:82 Offset]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:116 OffsetPosition]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:108 SpringArmTargetPosition]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:76 CameraBinding]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:99 CameraNode]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:93 GimbalHorizontalNode]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:96 GimbalVerticalNode]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:91 OffsetNode]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:68 PlayerCameraChunk]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:84 Settings]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCameraSettings.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:101 SpringArmTarget]]
                --
                [Interface Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:218 UsePlayerCamera()]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:210 _Input()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:62 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:220 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:185 OnPhysicsProcess()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:160 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCamera.cs:120 Setup()]]
            }
            class PlayerCameraSettings  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCameraSettings.cs ScriptFile]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCameraSettings.cs:11 JoypadSensitivity]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCameraSettings.cs:8 MouseSensitivity]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCameraSettings.cs:17 VerticalMax]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player_camera/PlayerCameraSettings.cs:23 VerticalMin]]
            }
            PlayerCamera::PlayerCameraSettings ---> PlayerCameraSettings
        }
        package Player-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.tscn]] {
            class Player  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:65 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:68 AppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
                [Provisions]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:59 IPlayerLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/state/states/PlayerLogic.State.Disabled.cs Script]]
                --
                [Interface Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:110 PlayerLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/state/states/PlayerLogic.State.Disabled.cs Script]]
                [Nodes]
                PlayerModel - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/PlayerModel.tscn Script]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:92 Acceleration]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:265 CenterOfMass]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:84 Gravity]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:103 JumpForce]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:96 JumpImpulseForce]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:88 MoveSpeed]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:113 PlayerBinding]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:54 PlayerChunk]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:76 RotationSpeed]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:111 Settings]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:80 StoppingSpeed]]
                --
                [Interface Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:213 GetGlobalInputVector()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:229 GetNextRotationBasis()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:250 IsMovingHorizontally()]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:46 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:271 Kill()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:156 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:189 OnPhysicsProcess()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:154 OnReady()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:163 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:258 Push()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:117 Setup()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/Player.cs:208 ShouldJump()]]
            }
            class PlayerModel << (S,black) >> {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/PlayerModel.tscn SceneFile]]
                [Nodes]
                chicken - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/player/visuals/chicken/chicken.tscn Script]]
            }
            Player::PlayerModel ---> PlayerModel
        }
        package Map-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.tscn]] {
            class Map  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:43 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                terrain - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/terrain/terrain.tscn Script]]
                DeathPlane - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_plane/DeathPlane.cs Script]]
                Tree1Geo - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo34 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo13 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo3 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo6 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo9 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo12 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo26 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo27 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo28 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo30 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo31 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo32 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo33 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo35 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo37 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo38 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo41 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo42 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo43 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo14 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo15 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo17 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo18 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo21 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                Tree1Geo24 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/trees/tree.tscn Script]]
                TreeTrunkSmall2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                TreeTrunkSmall - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                LargeTreeTrunk - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/large_tree_trunk/LargeTreeTrunk.tscn Script]]
                Jumpshroom2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom4 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom3 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom5 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom9 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom6 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom8 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom7 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Bush1 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush3 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush4 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush7 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush5 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Bush6 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/bushes/bush.tscn Script]]
                Coin - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin26 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin27 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin28 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin29 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin30 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin43 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin44 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin31 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin32 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin42 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin33 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin19 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin24 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin25 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin20 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin22 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin3 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin4 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin9 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin12 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin15 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin16 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin13 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin14 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin38 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin39 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin41 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin37 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin5 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin6 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin7 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin8 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin10 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin40 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin17 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin11 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin34 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                Coin36 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                TreeTrunkSmall - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                Jumpshroom - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Fence - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence3 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence4 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence8 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence12 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence13 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence9 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence10 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence11 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence14 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence15 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence16 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence17 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence5 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence6 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence7 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/fence/Fence.tscn Script]]
                Cloud - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud2 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud3 - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/cloud/Cloud.tscn Script]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:37 Coins]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:30 MapChunk]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:44 MapLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/state/MapLogic.Data.cs Script]]
                --
                [Interface Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:48 GetCoinCount()]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:21 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:52 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/Map.cs:50 Setup()]]
            }
            class terrain << (S,black) >> {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/terrain/terrain.tscn SceneFile]]
                [Nodes]
                Waterfall - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/map/waterfall/waterfall.tscn Script]]
            }
            class DeathPlane  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_plane/DeathPlane.cs ScriptFile]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_plane/DeathPlane.cs:10 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_plane/DeathPlane.cs:16 OnBodyEntered()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_plane/DeathPlane.cs:14 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_plane/DeathPlane.cs:12 OnReady()]]
            }
            class Jumpshroom  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:50 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:42 AnimationPlayer]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:43 Area3D]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:44 CooldownTimer]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:35 ImpulseStrength]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:32 JumpshroomBinding]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:30 JumpshroomLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/state/JumpshroomLogic.Data.cs Script]]
                --
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:19 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:102 OnAnimationFinished()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:84 OnAreaBodyEntered()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:82 OnCooldownTimeout()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:105 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:60 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:94 OnShroomLoaded()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/jumpshroom/Jumpshroom.cs:54 Setup()]]
            }
            class Coin  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:34 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Interface Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:36 CoinLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/state/states/CoinLogic.State.Collecting.cs Script]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:21 AnimationPlayer]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:39 CoinBinding]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:22 CoinModel]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:28 CollectionTimeInSeconds]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:45 CollectorDetector]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:37 Settings]]
                --
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:17 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:110 OnCollectorDetectorBodyEntered()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:120 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:107 OnPhysicsProcess()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:62 OnReady()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:77 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs:50 Setup()]]
            }
            Map::terrain ---> terrain
            Map::DeathPlane ---> DeathPlane
            Map::Jumpshroom2 ---> Jumpshroom
            Map::Coin ---> Coin
        }
        package InGameUI-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.tscn]] {
            class InGameUI  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:20 AppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:21 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                CoinScene - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn Script]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:68 AccessibilityLive]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:27 CoinsLabel]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:35 InGameUIBinding]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:33 InGameUILogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/state/InGameUILogic.cs Script]]
                --
                [Interface Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:59 SetCoinsLabel()]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:16 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:69 GetAccessibilityLive()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:62 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:41 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/InGameUI.cs:39 Setup()]]
            }
            package CoinScene-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn]] {
                class CoinScene << (S,black) >> {
                    [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn SceneFile]]
                    [Nodes]
                    UICoin - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/coin/Coin.cs Script]]
                }

                CoinScene::UICoin ---> Coin
            }
            class InGameUILogic  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/state/InGameUILogic.cs ScriptFile]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/state/InGameUILogic.cs:19 GetInitialState()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/state/InGameUILogic.cs:21 OnStart()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_ui/state/InGameUILogic.cs:30 OnStop()]]
            }
            InGameUI::CoinScene ---> CoinScene
            InGameUI::InGameUILogic ---> InGameUILogic
        }
        package InGameAudio-Scene [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.tscn]] {
            class InGameAudio  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs ScriptFile]]
                [Dependencies]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:26 AppRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/app/domain/AppRepo.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:28 GameRepo]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                GameMusic - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                MainMenuMusic - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:16 Bounce]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:15 CoinCollected]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:20 GameMusic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:36 InGameAudioBinding]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:34 InGameAudioLogic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/state/InGameAudioLogic.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:19 MainMenuMusic]] - [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:17 PlayerDied]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:18 PlayerJumped]]
                --
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:11 _Notification()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:71 OnExitTree()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:42 OnResolved()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:40 Setup()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:84 StartGameMusic()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/InGameAudio.cs:77 StartMainMenuMusic()]]
            }
            class DimmableAudioStreamPlayer  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs ScriptFile]]
                [Properties]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:23 FadeTween]]
                --
                [Interface Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:33 FadeIn()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:39 FadeOut()]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:27 _Ready()]]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:45 SetupFade()]]
            }
            class InGameAudioLogic  {
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/state/InGameAudioLogic.cs ScriptFile]]
                [Methods]
                [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/in_game_audio/state/InGameAudioLogic.cs:13 GetInitialState()]]
            }
            InGameAudio::GameMusic ---> DimmableAudioStreamPlayer
            InGameAudio::InGameAudioLogic ---> InGameAudioLogic
        }
        class DeathMenu  {
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:71 AccessibilityLive]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:38 AnimationPlayer]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:39 FadeAnimationPlayer]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:37 MainMenuButton]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:36 TryAgainButton]]
            --
            [Interface Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:57 Animate()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:60 FadeIn()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:62 FadeOut()]]
            [Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:23 _Notification()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:72 GetAccessibilityLive()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:68 OnAnimationFinished()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:50 OnExitTree()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:66 OnMainMenuPressed()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:43 OnReady()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/death_menu/DeathMenu.cs:64 OnTryAgainPressed()]]
        }
        class WinMenu  {
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:53 AccessibilityLive]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:26 AnimationPlayer]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:25 MainMenuButton]]
            --
            [Interface Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:46 FadeIn()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:51 FadeOut()]]
            [Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:21 _Notification()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:54 GetAccessibilityLive()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:48 OnAnimationFinished()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:42 OnExitTree()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:44 OnMainMenuPressed()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/win_menu/WinMenu.cs:40 OnReady()]]
        }
        class PauseMenu  {
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:88 AccessibilityLive]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:32 AnimationPlayer]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:31 MainMenuButton]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:29 ResumeButton]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:30 SaveButton]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:34 SaveOverlay]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:33 SaveOverlayAnimationPlayer]]
            --
            [Interface Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:74 FadeIn()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:79 FadeOut()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:82 OnSaveCompleted()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:81 OnSaveStarted()]]
            [Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:25 _Notification()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:85 Animate()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:89 GetAccessibilityLive()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:76 OnAnimationFinished()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:62 OnExitTree()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:70 OnMainMenuPressed()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:54 OnReady()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:71 OnResumePressed()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/pause_menu/PauseMenu.cs:72 OnSavePressed()]]
        }
        class GameRepo  {
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs ScriptFile]]
            [Constructors]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:124 GameRepo]]()
            [Interface Properties]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:106 CameraBasis]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:109 GlobalCameraDirection]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:99 IsMouseCaptured]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:101 IsPaused]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:113 NumCoinsAtStart]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:111 NumCoinsCollected]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:103 PlayerGlobalPosition]]
            --
            [Interface Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:167 OnFinishCoinCollection()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:183 OnGameEnded()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:181 OnJump()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:202 OnJumpshroomUsed()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:190 Pause()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:196 Resume()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:157 SetCameraBasis()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:154 SetIsMouseCaptured()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:204 SetNumCoinsAtStart()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:207 SetNumCoinsCollected()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:151 SetPlayerGlobalPosition()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:160 StartCoinCollection()]]
            [Methods]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:212 Dispose()]]
            [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/game/domain/GameRepo.cs:230 Dispose()]]
        }
        Game::PlayerCamera ---> PlayerCamera
        Game::Player ---> Player
        Game::Map ---> Map
        Game::InGameUi ---> InGameUI
        Game::InGameAudio ---> InGameAudio
        Game::DeathMenu ---> DeathMenu
        Game::WinMenu ---> WinMenu
        Game::PauseMenu ---> PauseMenu
        Game::GameRepo ---> GameRepo
    }
    class Instantiator  {
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/utils/Instantiator.cs ScriptFile]]
        [Interface Properties]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/utils/Instantiator.cs:27 SceneTree]]
        --
        [Interface Methods]
        [[vscode://file//mnt/Data/StaticLibGodotExample/GameDemo/src/utils/Instantiator.cs:34 LoadAndInstantiate()]]
    }
    App::Menu ---> Menu
    App::Splash ---> Splash
    App::AppRepo ---> AppRepo
    App::Game ---> Game
    App::Instantiator ---> Instantiator
}

@enduml